services:
  # ================= BACKEND =================
  - type: web
    name: worker-fatigue-backend
    env: python
    plan: free
    region: oregon
    branch: main

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker

    healthCheckPath: /

  # ================= FRONTEND =================
  - type: web
    name: worker-fatigue-frontend
    env: static
    branch: main

    buildCommand: |
      cd frontend
      npm install
      npm run build

    staticPublishPath: frontend/dist

    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    
  envVars:
      - key: VITE_API_URL
        value: https://worker-fatigue-backend.onrender.com/api
