import { useState, useEffect } from 'react';
import { FileText, Download, Calendar, RefreshCw } from 'lucide-react';
import api from '../utils/api';

const Reports = () => {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    loadSummary();
  }, []);

  const loadSummary = async () => {
    setLoading(true);
    try {
      const data = await api.getAnalyticsSummary();
      if (data.status === 'success') {
        setSummary(data);
      }
    } catch (err) {
      console.error('Failed to load summary:', err);
    }
    setLoading(false);
  };

  const exportCSV = () => {
    if (!summary || !summary.statistics) return;

    const stats = summary.statistics;
    const csv = [
      ['Metric', 'Value'],
      ['Average Fatigue (%)', stats.avg_fatigue.toFixed(2)],
      ['Average Stress (%)', stats.avg_stress.toFixed(2)],
      ['Average Risk Score', stats.avg_risk.toFixed(2)],
      ['Maximum Risk', stats.max_risk.toFixed(2)],
      ['Minimum Risk', stats.min_risk.toFixed(2)],
      ['Total Samples', stats.total_samples],
      ['Session Duration (min)', summary.session_info?.duration_minutes?.toFixed(2) || '0']
    ].map(row => row.join(',')).join('\n');

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fatigue-report-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
  };

  const generatePDFContent = () => {
    if (!summary || !summary.statistics) return;

    const stats = summary.statistics;
    const content = `
WORKER FATIGUE & STRESS DETECTION REPORT
Generated: ${new Date().toLocaleString()}

SESSION INFORMATION
─────────────────────────────────────
Start Time: ${summary.session_info?.start_time ? new Date(summary.session_info.start_time).toLocaleString() : 'N/A'}
Duration: ${summary.session_info?.duration_minutes?.toFixed(2) || '0'} minutes
Total Samples: ${stats.total_samples}

KEY METRICS
─────────────────────────────────────
Average Fatigue Level: ${stats.avg_fatigue.toFixed(2)}%
Average Stress Level: ${stats.avg_stress.toFixed(2)}%
Average Risk Score: ${stats.avg_risk.toFixed(2)}

RISK ANALYSIS
─────────────────────────────────────
Minimum Risk: ${stats.min_risk.toFixed(2)}
Maximum Risk: ${stats.max_risk.toFixed(2)}
Risk Range: ${(stats.max_risk - stats.min_risk).toFixed(2)}

RECOMMENDATIONS
─────────────────────────────────────
${stats.avg_risk > 70 ? '⚠ CRITICAL: Immediate intervention recommended' : 
  stats.avg_risk > 40 ? '⚡ WARNING: Monitor closely and consider break' :
  '✓ NORMAL: Continue regular monitoring'}

${stats.avg_fatigue > 60 ? '• High fatigue detected - Consider scheduling breaks' : ''}
${stats.avg_stress > 60 ? '• Elevated stress levels - Review workload and environment' : ''}

──────────────────────────────────────────────────────
Report generated by WorkerGuard Fatigue Detection System
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fatigue-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
  };

  const getRiskLevel = (score) => {
    if (score >= 71) return { label: 'Critical', color: '#ef4444' };
    if (score >= 41) return { label: 'Warning', color: '#f59e0b' };
    return { label: 'Normal', color: '#10b981' };
  };

  return (
    <div style={{ padding: '2rem', maxWidth: '1200px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '2rem', fontWeight: '700', color: 'white', marginBottom: '0.5rem' }}>
          Reports & Export
        </h1>
        <p style={{ color: 'rgba(255,255,255,0.8)' }}>
          Generate and download session reports
        </p>
      </div>

      {/* Quick Actions */}
      <div className="card" style={{ marginBottom: '1.5rem' }}>
        <h3 style={{ fontSize: '1.125rem', fontWeight: '600', marginBottom: '1.5rem' }}>
          Quick Actions
        </h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
          <button
            onClick={exportCSV}
            className="btn-primary"
            style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}
            disabled={!summary || summary.status === 'no_data'}
          >
            <Download size={18} />
            Export CSV
          </button>
          
          <button
            onClick={generatePDFContent}
            className="btn-primary"
            style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}
            disabled={!summary || summary.status === 'no_data'}
          >
            <FileText size={18} />
            Export Report
          </button>
          
          <button
            onClick={loadSummary}
            className="btn-secondary"
            style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}
          >
            <RefreshCw size={18} />
            Refresh Data
          </button>
        </div>
      </div>

      {/* Session Summary */}
      {summary && summary.status === 'success' ? (
        <>
          <div className="card" style={{ marginBottom: '1.5rem' }}>
            <h3 style={{ fontSize: '1.125rem', fontWeight: '600', marginBottom: '1.5rem' }}>
              Session Summary
            </h3>
            
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1.5rem' }}>
              <div>
                <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  <Calendar size={16} style={{ display: 'inline', marginRight: '0.5rem' }} />
                  Session Start
                </p>
                <p style={{ fontSize: '1.125rem', fontWeight: '600' }}>
                  {summary.session_info?.start_time 
                    ? new Date(summary.session_info.start_time).toLocaleString()
                    : 'N/A'}
                </p>
              </div>
              
              <div>
                <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  Duration
                </p>
                <p style={{ fontSize: '1.125rem', fontWeight: '600' }}>
                  {summary.session_info?.duration_minutes?.toFixed(0) || '0'} minutes
                </p>
              </div>
              
              <div>
                <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  Total Frames Analyzed
                </p>
                <p style={{ fontSize: '1.125rem', fontWeight: '600' }}>
                  {summary.session_info?.total_frames || summary.statistics.total_samples}
                </p>
              </div>
              
              <div>
                <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  Overall Status
                </p>
                <span style={{
                  display: 'inline-block',
                  padding: '0.25rem 0.75rem',
                  borderRadius: '12px',
                  fontSize: '0.875rem',
                  fontWeight: '600',
                  background: `${getRiskLevel(summary.statistics.avg_risk).color}20`,
                  color: getRiskLevel(summary.statistics.avg_risk).color
                }}>
                  {getRiskLevel(summary.statistics.avg_risk).label}
                </span>
              </div>
            </div>
          </div>

          {/* Detailed Statistics */}
          <div className="card">
            <h3 style={{ fontSize: '1.125rem', fontWeight: '600', marginBottom: '1.5rem' }}>
              Detailed Statistics
            </h3>
            
            <div style={{ 
              display: 'grid', 
              gridTemplateColumns: 'repeat(3, 1fr)', 
              gap: '1.5rem',
              paddingBottom: '1.5rem',
              borderBottom: '1px solid var(--border-color)'
            }}>
              <div>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  Average Fatigue
                </p>
                <p style={{ fontSize: '1.75rem', fontWeight: '700', color: '#667eea' }}>
                  {summary.statistics.avg_fatigue.toFixed(1)}%
                </p>
              </div>
              
              <div>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  Average Stress
                </p>
                <p style={{ fontSize: '1.75rem', fontWeight: '700', color: '#764ba2' }}>
                  {summary.statistics.avg_stress.toFixed(1)}%
                </p>
              </div>
              
              <div>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  Average Risk Score
                </p>
                <p style={{ fontSize: '1.75rem', fontWeight: '700', color: getRiskLevel(summary.statistics.avg_risk).color }}>
                  {summary.statistics.avg_risk.toFixed(1)}
                </p>
              </div>
            </div>

            <div style={{ 
              display: 'grid', 
              gridTemplateColumns: 'repeat(2, 1fr)', 
              gap: '1.5rem',
              marginTop: '1.5rem'
            }}>
              <div>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  Minimum Risk Detected
                </p>
                <p style={{ fontSize: '1.25rem', fontWeight: '600' }}>
                  {summary.statistics.min_risk.toFixed(2)}
                </p>
              </div>
              
              <div>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  Maximum Risk Detected
                </p>
                <p style={{ fontSize: '1.25rem', fontWeight: '600' }}>
                  {summary.statistics.max_risk.toFixed(2)}
                </p>
              </div>
            </div>

            {/* Recommendations */}
            <div style={{
              marginTop: '1.5rem',
              padding: '1rem',
              background: summary.statistics.avg_risk > 70 
                ? 'rgba(239, 68, 68, 0.1)'
                : summary.statistics.avg_risk > 40
                ? 'rgba(245, 158, 11, 0.1)'
                : 'rgba(16, 185, 129, 0.1)',
              borderRadius: '8px',
              border: `1px solid ${getRiskLevel(summary.statistics.avg_risk).color}`
            }}>
              <p style={{ 
                fontSize: '0.875rem', 
                fontWeight: '600', 
                marginBottom: '0.5rem',
                color: getRiskLevel(summary.statistics.avg_risk).color
              }}>
                Recommendations
              </p>
              <ul style={{ 
                fontSize: '0.875rem', 
                paddingLeft: '1.25rem',
                color: 'var(--text-primary)',
                lineHeight: '1.6'
              }}>
                {summary.statistics.avg_risk > 70 && (
                  <>
                    <li>Critical risk level detected - immediate intervention recommended</li>
                    <li>Schedule mandatory break for affected workers</li>
                    <li>Review and adjust shift schedules</li>
                  </>
                )}
                {summary.statistics.avg_risk > 40 && summary.statistics.avg_risk <= 70 && (
                  <>
                    <li>Warning level - monitor closely for next hour</li>
                    <li>Consider implementing short rest breaks</li>
                    <li>Check environmental factors (temperature, lighting, noise)</li>
                  </>
                )}
                {summary.statistics.avg_risk <= 40 && (
                  <>
                    <li>Normal operating conditions maintained</li>
                    <li>Continue regular monitoring schedule</li>
                  </>
                )}
                {summary.statistics.avg_fatigue > 60 && (
                  <li>High fatigue levels - ensure adequate rest periods</li>
                )}
                {summary.statistics.avg_stress > 60 && (
                  <li>Elevated stress - review workload distribution and task complexity</li>
                )}
              </ul>
            </div>
          </div>
        </>
      ) : (
        <div className="card" style={{ textAlign: 'center', padding: '3rem' }}>
          <FileText size={48} style={{ color: 'var(--text-secondary)', margin: '0 auto 1rem' }} />
          <h3 style={{ fontSize: '1.25rem', fontWeight: '600', marginBottom: '0.5rem' }}>
            No Data Available
          </h3>
          <p style={{ color: 'var(--text-secondary)' }}>
            Start live monitoring to generate reports
          </p>
        </div>
      )}
    </div>
  );
};

export default Reports;